name: questsme_ui
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.0
  intl: ^0.18.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Light.ttf
          weight: 300
        - asset: assets/fonts/Rowdies-Regular.ttf
        - asset: assets/fonts/Rowdies-Bold.ttf
          weight: 700
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
